#!/usr/bin/env bash
# LLDB-attached GL launcher (Tool 3, 2026-05-19).
#
# Wraps a single run-benchmark.sh invocation under LLDB so any segfault
# / abort during the GL leg yields a captured backtrace instead of an
# opaque exit-137. Primary use: the Halo cold-launch segfault path that
# infra-blocks paired Metal-vs-GL evidence on benchmark-runs/
# 20260511-153638-metal-gl-compare-halo (per handoff.md).
#
# Codex review 2026-05-19 (finding #4): direct `lldb -- xemu` bypasses
# run-benchmark.sh's run-dir, scratch HDD, QMP socket, snapshot,
# scripted-input, and cleanup machinery. This wrapper instead injects
# LLDB as the XEMU_BENCH_LAUNCHER_PREFIX so run-benchmark.sh creates
# the run dir, copies HDD, builds config, launches xemu under LLDB,
# tears down via QMP-quit, and emits perf summary normally. The LLDB
# output is captured to crash.lldb.log inside the run dir.
#
# Usage:
#   lldb-gl-launch.sh <game> [<input.csv>] [<duration>]
#
# Same positional args as run-benchmark.sh. Forces XEMU_RENDERER=GL.
# Operator overrides any other env via the calling environment.
#
# Output:
#   benchmark-runs/<ts>-<game>/
#     crash.lldb.log    LLDB stdout/stderr; bt/thread output on crash
#     xemu.log          xemu's own stdout/stderr (as usual)
#     ...               (everything else run-benchmark.sh writes)
#
# Limitations:
#   - LLDB --batch returns the inferior's exit status when normal; on
#     segfault it returns lldb's own exit code, not the signal. Read
#     crash.lldb.log to confirm whether the inferior crashed vs exited
#     cleanly.
#   - On the first run, macOS may prompt for Developer Tools usage
#     consent. If you see "operation could not be completed", run
#     `DevToolsSecurity -enable` or grant via System Settings.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUN_BENCHMARK="${ROOT_DIR}/scripts/apple-silicon/run-benchmark.sh"

usage() {
    cat <<EOF
usage: $0 <game> [<input.csv>] [<duration>]

Wraps run-benchmark.sh GL leg under LLDB so segfaults yield captured
backtraces (crash.lldb.log inside the run dir).

Required:
  <game>                crimson|rainbow|pgr2|sc2|halo|flat-tri-depth

Optional positional (forwarded to run-benchmark.sh):
  <input.csv>           Scripted-input CSV. Default: per-alias.
  <duration>            Default 180.

Environment:
  XEMU_BENCH_*          Forwarded to run-benchmark.sh.
  XEMU_RENDERER is forced to GL by this wrapper.

EOF
}

if [[ $# -lt 1 ]]; then usage >&2; exit 2; fi
case "$1" in -h|--help) usage; exit 0 ;; esac

if ! command -v lldb >/dev/null 2>&1; then
    echo "lldb not found in PATH. Install Xcode command-line tools." >&2
    exit 2
fi

# The launcher prefix is what run-benchmark.sh prepends to the final
# `xemu` exec. LLDB runs the process, dumps thread list + backtraces
# on any non-clean exit, then quits. -k / --one-line-on-crash commands
# run only if the inferior crashes.
#
# We DO NOT add LLDB --output-path / --error-path (older Apple LLDB
# builds reject those flags as unknown). Instead we let LLDB inherit
# the redirections run-benchmark.sh already installs:
#     "$XEMU" ... > "$LOG_FILE" 2>&1 &
# expands to
#     lldb ... -- "$XEMU" ... > "$LOG_FILE" 2>&1 &
# so both LLDB's own output and the inferior's pass-through stream
# land in xemu.log inside the run dir. After the run completes we
# copy xemu.log to crash.lldb.log so the operator has a clearly-named
# artifact to read.
#
# Lifecycle: run-benchmark.sh waits "$DURATION" then QMP-quits xemu.
# Under LLDB that quit reaches xemu normally; LLDB sees the process
# exit and prints the exit code. On crash, the -k commands run and
# print the backtrace before LLDB exits.
# Multi-word LLDB commands (`thread backtrace all`, `process status`)
# cannot survive bash word-splitting when the prefix is a single
# variable expanded inline inside run-benchmark.sh. Even
# `${LAUNCHER_PREFIX}` unquoted strips embedded quotes, so `-o 'process
# status'` becomes three tokens and LLDB then mishandles them.
#
# Workaround: write a tiny wrapper shell script with the full LLDB
# invocation (correctly quoted) and use its path — a single word — as
# the launcher prefix. The wrapper forwards "$@" so run-benchmark.sh's
# trailing `"$XEMU" -config_path ... ` args reach LLDB intact.
ON_CRASH_FILE="$(mktemp -t lldb-on-crash.XXXXX.cmds)"
WRAPPER_FILE="$(mktemp -t lldb-gl-wrapper.XXXXX.sh)"
INFERIOR_OUT="$(mktemp -t lldb-inferior.XXXXX.log)"
cat > "$ON_CRASH_FILE" <<'CMDS'
thread list
thread backtrace all
process status
register read
image list
CMDS

cat > "$WRAPPER_FILE" <<EOF
#!/bin/bash
# Auto-generated by lldb-gl-launch.sh; sources ${ON_CRASH_FILE} on crash.
#
# \`process launch -o <path> -e <path>\` redirects the inferior's stdout
# and stderr to known files; lldb otherwise allocates a pty in --batch
# mode and the inferior's output is lost. We dump the captured output
# into the run dir's crash.lldb.log after the run completes.
exec lldb --batch \\
    --source-on-crash "${ON_CRASH_FILE}" \\
    -o "process launch -o ${INFERIOR_OUT} -e ${INFERIOR_OUT}" \\
    -o "process status" \\
    -o "quit" \\
    -- "\$@"
EOF
chmod +x "$WRAPPER_FILE"

# Single-word launcher prefix — bash word-splitting is now a no-op.
LAUNCHER_PREFIX="$WRAPPER_FILE"

export XEMU_BENCH_LAUNCHER_PREFIX="$LAUNCHER_PREFIX"
export XEMU_RENDERER=GL

# Forward all positional args to run-benchmark.sh.
LAUNCH_OUT="$(mktemp -t lldb-gl-launch-out.XXXXX.log)"
trap 'rm -f "$LAUNCH_OUT" "$ON_CRASH_FILE" "$WRAPPER_FILE" "$INFERIOR_OUT" 2>/dev/null || true' EXIT

set +e
"$RUN_BENCHMARK" "$@" | tee "$LAUNCH_OUT"
rc=${PIPESTATUS[0]}
set -e

RUN_DIR="$(awk -F': ' '/^Run directory: / { print $2 }' "$LAUNCH_OUT" | tail -n 1)"
if [[ -n "$RUN_DIR" && -d "$RUN_DIR" ]]; then
    # crash.lldb.log = lldb's session output (target create / run / process status / on-crash) + the inferior's redirected stdout/stderr.
    {
        echo "=== LLDB session output (xemu.log) ==="
        cat "${RUN_DIR}/xemu.log" 2>/dev/null || true
        echo
        echo "=== Inferior stdout/stderr (process launch -o/-e) ==="
        cat "$INFERIOR_OUT" 2>/dev/null || true
    } > "${RUN_DIR}/crash.lldb.log"
    # Also fold the inferior output back into xemu.log so existing
    # tooling that reads xemu.log still finds the perf-interval lines.
    if [[ -s "$INFERIOR_OUT" ]]; then
        cat "$INFERIOR_OUT" >> "${RUN_DIR}/xemu.log"
    fi
    echo "lldb output:  ${RUN_DIR}/crash.lldb.log ($(wc -l < ${RUN_DIR}/crash.lldb.log | tr -d ' ') lines)"
fi

exit $rc
