/*
 * NV2A PGRAPH Metal renderer — shader-validation harness (slice M5).
 *
 * Per CLAUDE.md rule #1 ("no guessing") and metal-renderer-plan.md §6
 * R1, slice M5 must prove that the GLSL generated by the existing
 * `glsl/` generators round-trips through glslang → spirv-cross
 * (CompilerMSL) → `[device newLibraryWithSource:]` cleanly for a
 * representative sample of NV2A pipeline classes BEFORE the GLSL→MSL
 * cache is wired into the draw flow.
 *
 * This harness runs in-process (linked into the main xemu binary) at
 * `pgraph_mtl_init` time when the env-var
 * `XEMU_METAL_SHADER_VALIDATE=1` is set. It prints a per-fixture
 * pass/fail report to stderr, increments a fixed-name counter line
 * (METAL_SHADER_VALIDATE_OK / METAL_SHADER_VALIDATE_FAIL) on
 * `xemu-perf:`, and either continues init (XEMU_METAL_SHADER_VALIDATE
 * = 1) or exits the process (XEMU_METAL_SHADER_VALIDATE = strict)
 * once the report is done.
 *
 * The harness is also reachable from a unit-test driver in
 * scripts/apple-silicon/metal-shader-validation/run-validation.sh
 * (boots xemu without a disc image, sets the env var, captures the
 * stderr report).
 *
 * Copyright (c) 2026 XEMU MacOS Apple Silicon performance fork
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HW_XBOX_NV2A_PGRAPH_MTL_SHADER_VALIDATION_H
#define HW_XBOX_NV2A_PGRAPH_MTL_SHADER_VALIDATION_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Run the M5 shader-validation harness if XEMU_METAL_SHADER_VALIDATE
 * is set. Returns true if either:
 *   - the env var is unset (no-op), OR
 *   - the env var is set and every fixture passed.
 *
 * Returns false if any fixture failed (the harness still prints the
 * full per-fixture report to stderr). Caller decides whether to abort
 * init or proceed (M5 proceeds; the harness is advisory unless
 * XEMU_METAL_SHADER_VALIDATE=strict).
 */
bool pgraph_mtl_shader_validate_run(void);

/* Counters surfaced via util/xemu-metal-perf. Both are monotonic and
 * accumulate across multiple harness runs (e.g. one at startup + a
 * future periodic re-run). */
uint64_t pgraph_mtl_shader_validate_ok_count(void);
uint64_t pgraph_mtl_shader_validate_fail_count(void);

#ifdef __cplusplus
}
#endif

#endif /* HW_XBOX_NV2A_PGRAPH_MTL_SHADER_VALIDATION_H */
