XBE_TITLE       = alpha-test
GEN_XISO        = $(XBE_TITLE).iso
SRCS            = $(CURDIR)/main.c

XBED_LIB_DIR   ?= $(CURDIR)/../lib
include $(XBED_LIB_DIR)/lib.mk

NXDK_DIR       ?= /Users/jbbrack03/XEMU_MacOS/nxdk
include $(NXDK_DIR)/Makefile
