XBE_TITLE       = controller-readback
GEN_XISO        = $(XBE_TITLE).iso
SRCS            = $(CURDIR)/main.c
NXDK_DIR       ?= /Users/jbbrack03/XEMU_MacOS/nxdk
NXDK_SDL        = y

include $(NXDK_DIR)/Makefile
